name: CI Build

# This is a generic CI pipeline that assumes project is to be built as a container image
# Note. CI build only builds 'latest' image, not a versioned release

on:
  push:
    branches: [main]
    paths:
      - "**.go"
  pull_request:
    branches: [main]
    paths:
      - "**.go"

env:
  IMAGE_REG: ghcr.io
  IMAGE_NAME: benc-uk/mockery
  IMAGE_TAG: latest

permissions:
  packages: write

jobs:
  ci-build:
    name: Code Check & CI build
    runs-on: ubuntu-latest

    steps:
      # Checkout code from repo
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version-file: go.mod

      - name: Install tools
        run: make install-tools

      # Validate code
      - name: Check code for linting and format errors
        run: make lint

      # Run our tests
      - name: Run unit tests
        run: make test

      # Build image
      - name: Build the container image
        run: make image IMAGE_REPO=$GITHUB_ACTOR/$IMAGE_NAME

      # Only when pushing to default branch (e.g. master or main), then push image to registry
      - name: Push to container registry
        if: github.ref == 'refs/heads/main' && github.event_name == 'push'
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login $IMAGE_REG -u $GITHUB_ACTOR --password-stdin
          make push IMAGE_REPO=$GITHUB_ACTOR/$IMAGE_NAME
